### ISSUE TITLE
i hope you didn't give up on this

### ISSUE THREAD

**Issue by diomed** [Petertron/workspace_manager_b#3]
in symphony 2.5.2 upon installation I get blank page.
is there any hope you could update extension for next versions.  
this and 2.6. eventually.

**Comment by Petertron** [comment]
I am using Symphony 2.5.2 as well, and Workspace Manager B works for me. Can you check your error log and tell me what you find?

**Comment by diomed** [comment]
I can't seem to find my error log. :/

**Comment by twiro** [comment]
I do have the same problem (blank page, installation fails) when trying to install version 0.1.3 of this extension in Symphony 2.5.2.

This is what my error log is showing:

    PHP Parse error:  syntax error, unexpected '[' in .../extensions/workspace_manager_b/extension.driver.php on line 123

**Comment by Petertron** [comment]
So this is a syntax error which isn't a syntax error on PHP 5.5.9. Version 0.1.4 has been uploaded.

**Comment by diomed** [comment]
Thank you Peter. Now it installs fine & everything is good.
I just wonder how come symphonyextensions.com doesn't recognize it supports 2.5.2.
